#!/usr/bin/env bash
# Phase 107c — a picture TALLER THAN THE PAGER still draws its visible part

. "$(dirname "${BASH_SOURCE[0]}")/../lib.sh"
smoke_begin

# a picture TALLER THAN THE PAGER still draws its visible part
# (docs/images.md). Ctrl+O opens pinned to the bottom, so a tall picture starts
# *above* the window and its first visible row carries a non-zero row index —
# which the first version had no way to draw from, leaving a screenful of
# reserved-but-empty rows on the most ordinary open there is. A 100x600 PNG at
# a 5x10 cell on a 40-column terminal is 19 rows against an 11-row pager body,
# and the seeded session ENDS on the image, so the bottom-pinned open lands in
# the middle of it.
S107C="${S}_imageclip"
IMG_DIR3="$(mktemp -d "$SMOKE_TMP/imageclip.XXXXXX")"
IMG_SESS3="$(mktemp -d "$SMOKE_TMP/imgclipsess.XXXXXX")"
mkdir -p "$IMG_SESS3/2026/07/23"
base64 -d >"$IMG_DIR3/tall.png" <<'PNG64'
iVBORw0KGgoAAAANSUhEUgAAAGQAAAJYCAIAAAAbp9T8AAAcfUlEQVR4Ae3AA6AkWZbG8f937o3I
zKdyS2Oubdu2bdu2bdu2bWmMnpZKr54yMyLu+Xa3anqmhztr1a/aLvqjQguy0IIstCALLchCK7Qg
Cy3IQguy0IIstEILstCCLLQgCy3IQguy0AotyEILstCCLLQgC63Qgiy0IAstyEILstCCLLRCC7LQ
giy0IAstyEIrtCALLchCC7LQgiy0IAut0IIstCALLchCC7KQBQIKBBQIKBBQIKBAgYACAQUCCgQU
COlPuOpfBEBw1YsCgIq46l8GQHDViwKAirjqXwZAAK29Cle9cAAEUMofcdULB0BFXPUvAyC46kUB
QEVc9S8DILjqRQFARQDD8Orz/ne56gUBIACg73+fq14IAIKrXhQAVMRV/zIAgqteFABUxFX/MgCC
+61Wr8lVLwgAFXHFfPG7RVz1/AEQXPWiACC46kUBQEVc9S8DILjqRQFARTzL4eHrbG/+Blc9LwCC
B9jc/C2uer4AqIir/mUABFe9KAAIrnpRAFARV/3LAAie0/7+63HV8wKgIh5oe+c3irjquQEQXPWi
AKAirvqXARBc9aIAILjqRQFAIBAIBAKxe+kNEQgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAI
BAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCETyP48d/
laueCwAVcdW/DIDgqhcFABVx1b8MgOCqFwUAwfNz4cIbc9UDAVARz+vkqV8u4qpnAyC46kUBQEVc
9S8DILjqRQFAcNWLAoBAIBAIBAKBOHvuzRAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQC
gUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAhE8AKcOfMLXPUs
AFTEVf8yAIKrXhQAVMRV/zIAgqteFAAEL9i9974FV10BQEW8INde93NFXAUAQHDViwKAirjqXwZA
cNWLAoCKuOpfBkDwQt1111tzFQBA8ELdcMNPcxUAQEVc9S8DILjqRQFARVz1LwMguOpFAUAgEAgE
AoFAIBCI2+94OwQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAg
EAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBCI4F9y880/wVUABFe9KACoiKv+ZQAEV70oAKiI
q/5lAAQvgmc84x34fw6AivgXPejBP1bE/2sABFe9KAAIrnpRAFARV/3LAAiuelEAEAgEAoFAIBAI
BAKBeNrT3xmBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQC
gUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEIjgRfPQh/4w/58BUBFX/csACK56UQAQXPWiAKAirvqX
ARC8yJ7ylHfl/y0AKuJF9PBH/GAR/08BEFz1ogAguOpFAUBFXPUvAyC46kUBQCAQCAQCgUAgEAgE
AoF44pPeA4FAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKB
QCAQCAQCgUAgEAgEAoFAIBAIBAKBQCCCf41HPer7+P8JgIq46l8GQHDViwKA4KoXBQAVcdW/DIDg
X+nxj38v/h8CoCL+VR7z2O8p4v8dAIKrXhQAVMRV/zIAgqteFAAEV70oAAgEAoFAIBAIBAKBQCAQ
CMTf/8P7IhAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQ
CAQCgUAgEAgEAoFAIBAIBAKBQCAQwb/ei7/4d/L/DQAVcdW/DIDgqhcFABVx1b8MgOCqFwUAwb/J
3/7t+/P/CgAV8W/wki/17UX8PwJAcNWLAoCKuOpfBkBw1YsCgIq46l8GQPBv9Vd/9UH8/wFA8G/1
Mi/zLfz/AUBFXPUvAyC46kUBQEVc9S8DILjqRQFAIBAIBAKBQCAQCAQCgUAgEAjEn//FhyIQCAQC
gUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKB
QCAQCAQCgQj+HV7+5b+R/ycACK56UQBQEVf9ywAIrnpRAFARV/3LAAj+ff70Tz+c/w8ACP59XvEV
v57/DwCoiKv+ZQAEV70oAKiIq/5lAARXvSgACAQCgUAgEAgEAoFAIBAIBAKBQCD+6I8/CoFAIBAI
BAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgE
AoFAIBDBv9urvMrX8H8eAMFVLwoAKuKqfxkAwVUvCgAq4qp/GQDBf4Q/+IOP4f82ACri3+/VXv2r
ivi/DIDgqhcFAMFVLwoAKuKqfxkAwVUvCgACgUAgEAgEAoFAIBAIBAKBQCAQCATid3/v4xEIBAKB
QCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFA
IBAIRPAf5DVf88v5PwyAirjqXwZAcNWLAoDgqhcFABVx1b8MgOA/zm//9ifyfxUAFfEf5bVf50uL
+L8JgOCqFwUAFXHVvwyA4KoXBQDBVS8KAAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKB+I3f/BQEAoFA
IBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAg
EAhE8B/q9V7vi/g/CYCKuOpfBkBw1YsCgIq46l8GQHDViwKA4D/ar/3ap/F/DwAV8R/rDd7wC4r4
vwaA4KoXBQAVcdW/DIDgqhcFAMFVLwoAAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIH75Vz4TgUAg
EAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQ
CETwn+CN3/hz+T8GgIq46l8GQHDViwKAirjqXwZAcNWLAoDgP8cv/uJn838JABXxn+FN3+yzi/i/
A4DgqhcFABVx1b8MgOCqFwUAFXHVvwyA4D/Nz/3c5/F/BgDBf5q3eIvP4P8MACriqn8ZAMFVLwoA
KuKqfxkAwVUvCgACgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAjET//MFyIQCAQCgUAgEAgEAoFA
IBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIRPCf6a3f+lP5vwGA
4KoXBQAVcdW/DIDgqhcFABVx1b8MgOA/2U/+5BfzfwAAFfGf6m3f7pOL+F8PgOCqFwUAwVUvCgAq
4qp/GQDBVS8KAAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQC8WM//mUIBAKBQCAQCAQCgUAg
EAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAhE8J/vHd7hE/jfDoCK
uOpfBkBw1YsCgOCqFwUAFXHVvwyA4L/Ej/zIV/C/GgAV8V/gnd7544r4XwyA4KoXBQDBVS8KACri
qn8ZAMFVLwoAAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQPzgD301AoFAIBAIBAKBQCAQ
CAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCETwX+Vd3/Wj+d8LgIq4
6l8GQHDViwKA4KoXBQAVcdW/DIDgv9D3f//X8r8UABXxX+bd3+Mji/hfCYDgqhcFABVx1b8MgOCq
FwUAwVUvCgACgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBDf873fgEAgEAgEAoFAIBAI
BAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIRPBf673e68P43wiAirjq
XwZAcNWLAoCKuOpfBkBw1YsCgOC/3Hd91zfxvw4AFfFf7H3e90OK+F8GgOCqFwUAFXHVvwyA4KoX
BQAVcdW/DIDgv8O3f/u38r8LAMF/h/d//w/kfxcAKuKqfxkAwVUvCgAq4qp/GQDBVS8KAAKBQCAQ
CAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgE4lu+9TsQCAQCgUAgEAgEAoFAIBAIBAKBQCAQ
CAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAhE8N/kgz7o/fhfBIDgqhcFABVx1b8MgOCqFwUA
FXHVvwyA4L/PN33Td/G/BQDBf58P+ZD34X8LACriqn8ZAMFVLwoAKuKqfxkAwVUvCgACgUAgEAgE
AoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKB+Ppv+F4EAoFAIBAIBAKBQCAQCAQCgUAgEAgE
AoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIRPDf6sM//D35XwGA4KoXBQAVcdW/DIDgqhcFABVx
1b8MgOC/29d+7ffzPx8AFfHf6yM/6t2L+J8OgOCqFwUAwVUvCgAq4qp/GQDBVS8KAAKBQCAQCAQC
gUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIL7qq38IgUAgEAgEAoFAIBAIBAKBQCAQCAQC
gUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAhE8D/Ax3zMu/A/HAAVcdW/DIDgqhcFAMFVLwoAKuKq
fxkAwf8MX/EVP8L/ZABUxP8EH/fx71TE/1wABFe9KACoiKv+ZQAEV70oAAiuelEAEAgEAoFAIBAI
BAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUB86Zf9OAKBQCAQCAQCgUAgEAgEAoFAIBAI
BAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCCC/zE+8RPfnv+xAKiIq/5lAARXvSgAqIir/mUABFe9
KAAI/if54i/+Sf5nAqAi/uf45E952yL+JwIguOpFAUBFXPUvAyC46kUBQHDViwKAQCAQCAQCgUAg
EAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKB+IIv/BkEAoFAIBAIBAKBQCAQCAQCgUAg
EAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAhH8D/Npn/ZW/A8EQEVc9S8DILjqRQFARVz1LwMguOpF
AUDwP8/nfd7P8T8NABXxP81nfOZbFPE/CwDBVS8KACriqn8ZAMFVLwoAKuKqfxkAwf9In/3Zv8j/
KAAE/yN99me/Kf+jAFARV/3LAAiuelEAUBFX/csACK56UQAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQ
CAQCgUAgEAgEAoFAIBAIBAKBQCAQCATiMz7zVxAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQ
CAQCgUAgEAgEAoFAIIL/qT7v896I/zkACK56UQBQEVf9ywAIrnpRAFARV/3LAAj+B/u0T/s1/ocA
oCL+x/qCL3yDIv5HACC46kUBQHDViwKAirjqXwZAcNWLAoBAIBAIBAKBQCAQCAQCgUAgEAgEAoFA
IBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIxCd/ym8iEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFA
IBAIBAKBQCAQCAQCEfzP9sVf/Lr8TwBARVz1LwMguOpFAUBw1YsCgIq46l8GQPA/3id+4m/z3w6A
ivgf7ku/7LWL+G8GQHDViwKA4KoXBQAVcdW/DIDgqhcFAIFAIBAIBAKBQCAQCAQCgUAgEAgEAoFA
IBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBOLjPv73EAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFA
IBAIBAKBQCAQCAQi+N/gK77iNfjvBUBFXPUvAyC46kUBQHDViwKAirjqXwZA8L/Ex3zMH/DfCICK
+F/hq7761Yr4bwNAcNWLAoCKuOpfBkBw1YsCgOCqFwUAgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAg
EAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoH4yI/6YwQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAg
EAgEAoFAIBAIBCL43+Nrv/aV+e8CQEVc9S8DILjqRQFARVz1LwMguOpFAUDwv8qHf/if8t8CgIr4
X+Trv+EVi/hvAEBw1YsCgIq46l8GQHDViwKAirjqXwZA8L/Nh3zIX/BfD4Dgf5tv+qaX478eABVx
1b8MgOCqFwUAFXHVvwyA4KoXBQCBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFA
IBAIBAKBQCAQCAQCgUAgEB/4QX+NQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEIvhf
6Fu/9aX5LwZAcNWLAoCKuOpfBkBw1YsCgIq46l8GQPC/0/u//9/yXwmA4H+nb//2l+S/EgAVcdW/
DIDgqhcFABVx1b8MgOCqFwUAgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQ
CAQCgUAgEAgEAoFAIBAIxPu87z8gEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBCL4X+u7
vuvF+C8DQHDViwKAirjqXwZAcNWLAoCKuOpfBkDwv9l7vdfj+a8BQEX87/U93/uYIv4rABBc9aIA
ILjqRQFARVz1LwMguOpFAUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQC
gUAgEAgEAoFAIBAIBAKBQLz7ezwJgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFABP/Lff/3
P5L/AgBUxFX/MgCCq14UAARXvSgAqIir/mUABP/7veu7PoX/bABUxP92P/hDDy/iPxcAwVUvCgAq
4qp/GQDBVS8KAIKrXhQABAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAI
BAKBQCAQCAQCgUAgEAgEAvFO7/x0BAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCETwf8KP/MhD
+E8FQEVc9S8DILjqRQFARVz1LwMguOpFAUDwf8U7vMMz+M8DQEX83/BjP/6gIv6zABBc9aIAoCKu
+pcBEFz1ogAguOpFAUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAg
EAgEAoFAIBAIBAKBQCAQCMTbvt0dCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAggv9DfvInb+I/
CQAVcdW/DIDgqhcFABVx1b8MgOCqFwUAwf8tb/3Wd/GfAYCK+L/kp3/mhiL+4wEQXPWiAKAirvqX
ARBc9aIAoCKu+pcBEPyf8xZvcS//4QAI/s/5uZ+7lv9wAFTEVf8yAIKrXhQAVMRV/zIAgqteFAAE
AoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQC
gUAgEIg3fbNzCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCEfxf9Iu/eJr/WAAEV70oAKiIq/5lAARX
vSgAqIir/mUABP9HvfEbX+A/EAAV8X/SL//KySL+wwAQXPWiACC46kUBQEVc9S8DILjqRQFAIBAI
BAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgE
AoFAIN7gDS8hEAgEAoFAIBAIBAKBQCAQCAQCgUAgEMH/Xb/2a8f4jwJARVz1LwMguOpFAUBw1YsC
gIq46l8GQPB/2uu93j7/IQCoiP/DfuM3t4v4DwBAcNWLAoDgqhcFABVx1b8MgOCqFwUAgUAgEAgE
AoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQC
gUAgXvt1jhAIBAKBQCAQCAQCgUAgEAgEAoFAIIL/6377tzf49wOgIq76lwEQXPWiACC46kUBQEVc
9S8DIPh/4DVfc8W/EwAV8X/e7/7evIh/FwCCq14UAFTEVf8yAIKrXhQABFe9KAAIBAKBQCAQCAQC
gUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKB
QLzaq48IBAKBQCAQCAQCgUAgEAgEAoFABP8//MEfdPx7AFARV/3LAAiuelEAUBFX/csACK56UQAQ
/L/xKq/S+DcDoCL+n/ijPy5F/BsBEFz1ogCgIq76lwEQXPWiAKAirvqXARD8f/KKr2j+bQAI/j/5
0z8V/zYAVMRV/zIAgqteFABUxFX/MgCCq14UAAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgE
AoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAjEy728EQgEAoFAIBAIBAKB
QCAQCETw/8xf/IX4NwAguOpFAUBFXPUvAyC46kUBQEVc9S8DIPj/52VexvxrARD8//NXfyX+tQCo
iKv+ZQAEV70oAKiIq/5lAARXvSgAqIj/h17yJf33fytedAAE/y/97d+KfxUAgqteFABUxFX/MgCC
q14UAFTEVf8yAIL/r178xc2LDoCK+P/p7/9BRbyoAAiuelEAEFz1ogCgIq76lwEQXPWiAKAi/t96
zGP8xMeLFwUAwf9jj3+8eBEBUBFX/csACK56UQAQXPWiAKAirvqXARD8//aoR5kXBQAV8f/ZE5+k
Iv5lAARXvSgAqIir/mUABFe9KAAIrnpRAFAR/889/OF+2lPECwdA8P/eU54i/kUAVMRV/zIAgqte
FABUxFX/MgCCq14UAARXwUMfal44ACriqqc9XUW8MAAEV70oAKiIq/5lAARXvSgACK56UQBQEVcB
D3qQb3+GeEEACK667BnPEC8EABVx1b8MgOCqFwUAFXHVvwyA4KoXBQDBVfe7+WbzggBQEVddcfsd
KuL5AyC46kUBQEVc9S8DILjqRQFARVz1LwMguOoBbrjBPF8ABFc9wF13iecLgIq46l8GQHDViwKA
irjqXwZAcNWLAoCKuOqBrr3WZ+8VzwWA4KrndO+94nkBEFz1ogCgIq76lwEQXPWiAKAirvqXARBc
9TzOnDHPBYCKuOq5nD2nIp4DAMFVLwoAgqteFABUxFX/MgCCq14UAFTEVc/r5EnvXhDPAkBw1fNz
4YJ4IAAq4qp/GQDBVS8KAIKrXhQAVMRV/zIAgqtegOPHzbMAUBFXPV+7l1TEMwEQXPWiACC46kUB
QEVc9S8DILjqRQFARVz1gmxv+3BfAAAEV71g+/viCgAq4qp/GQDBVS8KAIKrXhQAVMRV/zIAgqte
qM1NAwBQEVe9EIdHKgIAgqteFABUxFX/MgCCq14UAARXvSgAqIirXrj53MNKQHDVv2S1EgBUxFX/
MgCCq14UAFTEVf8yAIKrXhQABFe9CPreQEVc9S8aRhURXPWiAKAirvqXARBc9aIAoCKu+pcBULnq
RQGluHLViwJaU0Vc9S8DILjqRQFARVz1LwMguOpFAcA/Ao9HoT6C64xuAAAAAElFTkSuQmCC
PNG64
img_file3="$IMG_SESS3/2026/07/23/rollout-2026-07-23T10-00-00-10710712.jsonl"
{
	printf '{"timestamp":"2026-07-23T10:00:00.000Z","type":"session_meta","payload":{"id":"smoke-107c","timestamp":"2026-07-23T10:00:00.000Z","cwd":"%s","model":"dummy_model_name","originator":"alter-zero","version":"0.1.0"}}\n' "$IMG_DIR3"
	printf '{"timestamp":"2026-07-23T10:00:01.000Z","type":"message","payload":{"role":"user","text":"look at tall.png","timestamp":"10:00 AM"}}\n'
	printf '{"timestamp":"2026-07-23T10:00:02.000Z","type":"tool","payload":{"name":"Read","args":"%s/tall.png","ok":true,"output":"Read image (PNG, 100x600, 9 KB)","timestamp":"10:00 AM","shell":false,"truncated":false,"arguments":"{\\"path\\":\\"%s/tall.png\\"}"}}\n' "$IMG_DIR3" "$IMG_DIR3"
} >"$img_file3"
IMG_ENV3="$CFG_ENV_NOHIST ALTER_ZERO_SESSIONS_DIR=$IMG_SESS3 ALTER_ZERO_IMAGE_PROTOCOL=halfblocks ALTER_ZERO_IMAGE_CELL_SIZE=5x10 ALTER_ZERO_STARTUP_DELAY_MS=$SMOKE_STARTUP_MS"
launch -c "$IMG_DIR3" "$S107C" 40 16 "env $IMG_ENV3 $BIN_ABS"
tmux send-keys -t "$S107C" -l "/resume"
sleep 0.3
tmux send-keys -t "$S107C" Enter
sleep 1.2
tmux send-keys -t "$S107C" Enter # load it
img_clip_loaded=0
for _ in $(seq 1 60); do
	if tmux capture-pane -t "$S107C" -p -S -60 | grep -qF "Read image (PNG, 100x600"; then
		img_clip_loaded=1
		break
	fi
	sleep 0.1
done
sleep 0.6
# A picture row is a non-blank line carrying none of the chrome's letters,
# digits or percent sign — the half-block glyphs are multibyte, which the C
# locale's character classes never match.
img_clip_inline="$(tmux capture-pane -t "$S107C" -p -S -60 | grep -v '[A-Za-z0-9%]' | grep -cve '^[[:space:]]*$')"
tmux send-keys -t "$S107C" C-o
sleep 1.5
img_clip_overlay="$(tmux capture-pane -t "$S107C" -p | grep -v '[A-Za-z0-9%]' | grep -cve '^[[:space:]]*$')"
echo "==== Phase 107c: tall picture — inline_rows=$img_clip_inline pager_rows=$img_clip_overlay ===="
tmux capture-pane -t "$S107C" -p | tail -4
tmux kill-session -t "$S107C" 2>/dev/null
rm -rf "$IMG_DIR3" "$IMG_SESS3"
if [ "$img_clip_loaded" != 1 ]; then
	fail "precondition — the seeded tall-image session never loaded"
fi
if [ "$img_clip_inline" -lt 15 ]; then
	fail "precondition — the fixture is not taller than the pager (inline drew only $img_clip_inline rows)"
fi
if [ "$img_clip_overlay" -lt 8 ]; then
	fail "the bottom-pinned Ctrl+O pager drew $img_clip_overlay rows of a picture whose head is above the window; a cut block must still draw its visible part"
fi
