#!/usr/bin/env bash
# scripts/release/selftest.sh — the release tooling's own tests.
#
#   scripts/release.sh selftest
#
# Every rule in lib.sh and every step is driven against a FIXTURE tree under
# a temp dir (RELEASE_ROOT points the steps at it), never the checkout: the
# readers over a manifest whose dependencies carry their own `version =`
# lines, the changelog grammar over a file with two releases, `check` against
# a consistent tree and then each way of breaking it, `package_dist` +
# `verify` over a real (tiny, C) binary so the CPU and `--version` checks run
# for real, `notes` over that dist, `prepare` rolling a fixture forward, and
# `publish --dry-run`. Needs only bash, awk, sed, tar, gzip, file and a C
# compiler (the binary cases are skipped without one). Runs in a second or
# two; CI runs it on every push and the release workflow before it builds.
set -uo pipefail
# shellcheck source-path=SCRIPTDIR
# shellcheck source=lib.sh
. "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/lib.sh"
set +e

STEPS="$RELEASE_LIB_DIR"
T="$(mktemp -d)"
trap 'rm -rf "$T"' EXIT
PASS=0
FAILED=0

pass() {
	PASS=$((PASS + 1))
	printf '  %sok%s  %s\n' "$_c_green" "$_c_off" "$*"
}
flunk() {
	FAILED=$((FAILED + 1))
	printf '  %sFAIL%s %s\n' "$_c_red" "$_c_off" "$*"
}
# expect_eq DESCRIPTION WANT GOT
expect_eq() {
	if [ "$2" = "$3" ]; then pass "$1"; else flunk "$1 — want '$2', got '$3'"; fi
}
# expect_ok DESCRIPTION CMD… — the command exits 0 (its output is kept in $OUT)
expect_ok() {
	local d="$1"
	shift
	if OUT="$("$@" 2>&1)"; then pass "$d"; else flunk "$d — exit $? — $OUT"; fi
}
# expect_fail DESCRIPTION CMD… — the command exits non-zero
expect_fail() {
	local d="$1"
	shift
	if OUT="$("$@" 2>&1)"; then flunk "$d — unexpectedly succeeded: $OUT"; else pass "$d"; fi
}
expect_contains() {
	case "$2" in
	*"$3"*) pass "$1" ;;
	*) flunk "$1 — '$3' not found in: $2" ;;
	esac
}
expect_lacks() {
	case "$2" in
	*"$3"*) flunk "$1 — '$3' unexpectedly found in: $2" ;;
	*) pass "$1" ;;
	esac
}
section() { printf '%s%s%s\n' "$_c_dim" "$*" "$_c_off"; }

# A release-ready fixture: version 0.4.2 everywhere, two releases in the
# changelog, an empty [Unreleased].
fixture() {
	local root="$1"
	mkdir -p "$root"
	cat >"$root/Cargo.toml" <<'EOF'
[package]
name = "alter-zero"
version = "0.4.2"
edition = "2024"
repository = "https://github.com/example/alter-zero.git"

[dependencies]
serde = { version = "1", features = ["derive"] }
other = "9.9.9"

[dev-dependencies]
version = "8.8.8"
EOF
	cat >"$root/Cargo.lock" <<'EOF'
# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "aho-corasick"
version = "1.1.3"

[[package]]
name = "alter-zero"
version = "0.4.2"
dependencies = [
 "aho-corasick",
 "version",
]

[[package]]
name = "version"
version = "8.8.8"
EOF
	cat >"$root/README.md" <<'EOF'
# Fixture

<a href="Cargo.toml"><img src="https://img.shields.io/badge/Version-0.4.2-89DCEB?style=for-the-badge&amp;logo=github" alt="Version: 0.4.2" height="32"></a>
<a href="LICENSE"><img src="https://img.shields.io/badge/License-Apache--2.0-A6E3A1?style=for-the-badge" alt="License: Apache 2.0" height="32"></a>
EOF
	cat >"$root/CHANGELOG.md" <<'EOF'
# Changelog

## [Unreleased]

## [0.4.2] - 2026-09-12

### Fixed

- A thing that was broken.

## [0.4.1] - 2026-09-01

### Added

- The thing.

[Unreleased]: https://github.com/example/alter-zero/compare/v0.4.2...HEAD
[0.4.2]: https://github.com/example/alter-zero/compare/v0.4.1...v0.4.2
[0.4.1]: https://github.com/example/alter-zero/releases/tag/v0.4.1
EOF
	printf 'Apache License\n' >"$root/LICENSE"
}

# ---------------------------------------------------------------------------
section "version grammar"
for v in 0.1.0 1.2.3 10.20.30 0.2.0-rc.1 1.0.0-beta+exp.sha.5114f85; do
	if is_semver "$v"; then pass "semver accepts $v"; else flunk "semver rejects $v"; fi
done
for v in v0.1.0 0.1 01.0.0 1.2.3.4 "" 1.2.3-; do
	if is_semver "$v"; then flunk "semver accepts '$v'"; else pass "semver rejects '$v'"; fi
done
expect_eq "tag_of" "v0.4.2" "$(tag_of 0.4.2)"
expect_eq "version_of_tag" "0.4.2" "$(version_of_tag v0.4.2)"
expect_fail "version_of_tag refuses a bare version" version_of_tag 0.4.2
expect_fail "version_of_tag refuses a non-semver tag" version_of_tag v0.4
if is_prerelease 0.2.0-rc.1; then pass "0.2.0-rc.1 is a pre-release"; else flunk "0.2.0-rc.1 not seen as a pre-release"; fi
if is_prerelease 0.2.0; then flunk "0.2.0 seen as a pre-release"; else pass "0.2.0 is not a pre-release"; fi

# ---------------------------------------------------------------------------
section "readers"
fixture "$T/fx"
export RELEASE_ROOT="$T/fx"
expect_eq "manifest version is [package]'s, not a dependency's" "0.4.2" "$(manifest_version)"
expect_eq "manifest name" "alter-zero" "$(manifest_name)"
expect_eq "manifest repository drops .git" "https://github.com/example/alter-zero" "$(manifest_repository)"
expect_eq "repo slug" "example/alter-zero" "$(repo_slug)"
expect_eq "lock version of the crate (not the crate named 'version')" "0.4.2" "$(lock_version alter-zero)"
expect_eq "lock version of another package" "8.8.8" "$(lock_version version)"
expect_eq "README badge label" "0.4.2" "$(readme_badge_version)"
expect_eq "README alt text" "0.4.2" "$(readme_alt_version)"
mkdir -p "$T/pre"
sed -e 's/Version-0\.4\.2-/Version-0.5.0--rc.1-/' -e 's/Version: 0\.4\.2/Version: 0.5.0-rc.1/' "$T/fx/README.md" >"$T/pre/README.md"
RELEASE_ROOT="$T/pre" expect_eq "README badge unescapes -- to -" "0.5.0-rc.1" "$(RELEASE_ROOT="$T/pre" readme_badge_version)"
expect_eq "badge_escape" "0.5.0--rc.1" "$(badge_escape 0.5.0-rc.1)"

# ---------------------------------------------------------------------------
section "changelog"
expect_eq "released versions, newest first" "0.4.2 0.4.1" "$(changelog_versions | tr '\n' ' ' | sed 's/ $//')"
expect_eq "heading date" "2026-09-12" "$(changelog_date 0.4.2)"
expect_eq "no date for an unknown version" "" "$(changelog_date 0.9.9)"
expect_eq "previous of 0.4.2" "0.4.1" "$(changelog_previous 0.4.2)"
expect_eq "previous of the first release" "" "$(changelog_previous 0.4.1)"
expect_eq "section body, trimmed" "### Fixed

- A thing that was broken." "$(changelog_section 0.4.2)"
expect_eq "last section stops before the link block" "### Added

- The thing." "$(changelog_section 0.4.1)"
expect_eq "empty [Unreleased]" "" "$(changelog_section Unreleased)"
expect_eq "link reference" "https://github.com/example/alter-zero/releases/tag/v0.4.1" "$(changelog_link 0.4.1)"

# ---------------------------------------------------------------------------
section "assets"
expect_eq "asset archive name" "alter-zero-v0.4.2-x86_64-unknown-linux-gnu.tar.gz" "$(asset_archive 0.4.2 x86_64-unknown-linux-gnu)"
expect_eq "asset_target parses the triple back" "aarch64-apple-darwin" "$(asset_target alter-zero-v0.4.2-aarch64-apple-darwin.tar.gz 0.4.2)"
expect_fail "asset_target refuses another version" asset_target alter-zero-v0.4.1-aarch64-apple-darwin.tar.gz 0.4.2
expect_fail "asset_target refuses a foreign name" asset_target notes.tar.gz 0.4.2
expect_eq "platform label" "macOS Apple silicon" "$(platform_label aarch64-apple-darwin)"
expect_eq "unknown platform falls back to the triple" "riscv64gc-unknown-linux-gnu" "$(platform_label riscv64gc-unknown-linux-gnu)"
expect_eq "format words" "ELF 64-bit|aarch64" "$(binary_format_words aarch64-unknown-linux-gnu)"
case "$(host_target)" in
*-unknown-linux-gnu | *-apple-darwin) pass "host target is $(host_target)" ;;
*) flunk "host target is $(host_target)" ;;
esac

# ---------------------------------------------------------------------------
section "check"
expect_ok "a consistent tree passes" bash "$STEPS/check.sh"
expect_ok "…and with its tag" bash "$STEPS/check.sh" v0.4.2
expect_fail "a tag for another version fails" bash "$STEPS/check.sh" v0.4.3
expect_contains "…naming the expected tag" "$OUT" "expected v0.4.2"
expect_fail "a malformed tag fails" bash "$STEPS/check.sh" 0.4.2
GITHUB_REF_TYPE=tag GITHUB_REF_NAME=v0.4.9 expect_fail "the workflow's tag variables are read" bash "$STEPS/check.sh"
GITHUB_REF_TYPE=branch GITHUB_REF_NAME=main expect_ok "a branch ref is not a tag" bash "$STEPS/check.sh"

fixture "$T/bad-lock" && sed 's/^version = "0.4.2"$/version = "0.4.1"/' "$T/fx/Cargo.lock" >"$T/bad-lock/Cargo.lock"
RELEASE_ROOT="$T/bad-lock" expect_fail "a stale Cargo.lock fails" bash "$STEPS/check.sh"
expect_contains "…and says so" "$OUT" "Cargo.lock records alter-zero 0.4.1"

fixture "$T/bad-readme" && sed 's/0\.4\.2/0.4.1/g' "$T/fx/README.md" >"$T/bad-readme/README.md"
RELEASE_ROOT="$T/bad-readme" expect_fail "a stale README badge fails" bash "$STEPS/check.sh"

fixture "$T/no-section" && sed '/^## \[0.4.2\]/,/^## \[0.4.1\]/{/^## \[0.4.1\]/!d;}' "$T/fx/CHANGELOG.md" >"$T/no-section/CHANGELOG.md"
RELEASE_ROOT="$T/no-section" expect_fail "a missing changelog section fails" bash "$STEPS/check.sh"
expect_contains "…pointing at prepare" "$OUT" "prepare"

fixture "$T/no-link" && grep -v '^\[0.4.2\]: ' "$T/fx/CHANGELOG.md" >"$T/no-link/CHANGELOG.md"
RELEASE_ROOT="$T/no-link" expect_fail "a missing link reference fails" bash "$STEPS/check.sh"

fixture "$T/no-changelog" && rm "$T/no-changelog/CHANGELOG.md"
RELEASE_ROOT="$T/no-changelog" expect_fail "a missing CHANGELOG.md fails" bash "$STEPS/check.sh"

fixture "$T/pending" && awk '/^## \[Unreleased\]$/ { print; print ""; print "### Added"; print ""; print "- Not yet rolled."; next } { print }' "$T/fx/CHANGELOG.md" >"$T/pending/CHANGELOG.md"
RELEASE_ROOT="$T/pending" expect_ok "pending [Unreleased] entries pass without a tag" bash "$STEPS/check.sh"
RELEASE_ROOT="$T/pending" expect_fail "…but fail on the release's tag" bash "$STEPS/check.sh" v0.4.2
expect_contains "…saying they were not rolled" "$OUT" "roll them into"

# ---------------------------------------------------------------------------
section "package + verify"
host="$(host_target)"
if command -v cc >/dev/null 2>&1; then
	cat >"$T/fake.c" <<'EOF'
#include <stdio.h>
#include <string.h>
int main(int argc, char **argv) {
	if (argc > 1 && strcmp(argv[1], "--version") == 0) { puts("alter-zero 0.4.2"); return 0; }
	return 1;
}
EOF
	if cc -o "$T/fake-bin" "$T/fake.c" 2>"$T/cc.log"; then
		archive="$(package_dist "$T/fake-bin" 0.4.2 "$host" "$T/dist")"
		expect_eq "package_dist names the archive" "$T/dist/alter-zero-v0.4.2-$host.tar.gz" "$archive"
		if [ -f "$archive.sha256" ]; then pass "…beside its .sha256"; else flunk "no .sha256 beside $archive"; fi
		expect_eq "the archive holds exactly the stem dir and four files" "alter-zero-v0.4.2-$host
alter-zero-v0.4.2-$host/CHANGELOG.md
alter-zero-v0.4.2-$host/LICENSE
alter-zero-v0.4.2-$host/README.md
alter-zero-v0.4.2-$host/alter-zero" "$(tar -tzf "$archive" | sed 's#/$##' | sort)"
		second="$(package_dist "$T/fake-bin" 0.4.2 "$host" "$T/dist2")"
		expect_eq "packaging is reproducible" "$(sha256_of "$archive")" "$(sha256_of "$second")"
		expect_ok "verify passes a good dist" bash "$STEPS/verify.sh" "$T/dist"
		expect_contains "…running --version on the host's asset" "$OUT" "alter-zero --version"
		expect_ok "verify takes an explicit version" bash "$STEPS/verify.sh" "$T/dist" --version 0.4.2
		expect_fail "verify refuses another version" bash "$STEPS/verify.sh" "$T/dist" --version 0.4.3
		expect_fail "verify refuses an empty dist" bash "$STEPS/verify.sh" "$T/empty-dist" 2>/dev/null || true
		mkdir -p "$T/empty-dist"
		expect_fail "verify refuses a dist with no archives" bash "$STEPS/verify.sh" "$T/empty-dist"

		cp -R "$T/dist" "$T/dist-badsum"
		printf '%s  %s\n' "0000000000000000000000000000000000000000000000000000000000000000" "$(basename "$archive")" >"$T/dist-badsum/$(basename "$archive").sha256"
		expect_fail "a wrong .sha256 fails" bash "$STEPS/verify.sh" "$T/dist-badsum"
		expect_contains "…naming the checksum" "$OUT" ".sha256"

		cp -R "$T/dist" "$T/dist-stray" && printf 'oops\n' >"$T/dist-stray/notes.txt"
		expect_fail "a stray file in dist fails" bash "$STEPS/verify.sh" "$T/dist-stray"
		expect_contains "…naming it" "$OUT" "notes.txt"

		cp -R "$T/dist" "$T/dist-sums" && cat "$T/dist-sums"/*.sha256 >"$T/dist-sums/SHA256SUMS"
		expect_ok "a SHA256SUMS agreeing with the per-asset files passes" bash "$STEPS/verify.sh" "$T/dist-sums"
		printf '%s  missing.tar.gz\n' "0000000000000000000000000000000000000000000000000000000000000000" >>"$T/dist-sums/SHA256SUMS"
		expect_fail "a SHA256SUMS naming a missing file fails" bash "$STEPS/verify.sh" "$T/dist-sums"

		mkdir -p "$T/dist-layout/x/alter-zero-v0.4.2-$host"
		cp "$T/fake-bin" "$T/dist-layout/x/alter-zero-v0.4.2-$host/alter-zero"
		cp "$T/fx/LICENSE" "$T/dist-layout/x/alter-zero-v0.4.2-$host/"
		tar_reproducible "$T/dist-layout/x" "alter-zero-v0.4.2-$host" "$T/dist-layout/alter-zero-v0.4.2-$host.tar.gz"
		write_sha256 "$T/dist-layout/alter-zero-v0.4.2-$host.tar.gz"
		rm -rf "$T/dist-layout/x"
		expect_fail "an archive missing README/CHANGELOG fails" bash "$STEPS/verify.sh" "$T/dist-layout"
		expect_contains "…as a layout problem" "$OUT" "unexpected layout"

		case "$host" in
		x86_64-*) other="${host/x86_64/aarch64}" ;;
		*) other="${host/aarch64/x86_64}" ;;
		esac
		package_dist "$T/fake-bin" 0.4.2 "$other" "$T/dist-cpu" >/dev/null
		expect_fail "a host binary labelled as $other fails the CPU check" bash "$STEPS/verify.sh" "$T/dist-cpu"
		expect_contains "…quoting file(1)" "$OUT" "file says"

		section "notes"
		expect_ok "notes render for a version with assets" bash "$STEPS/notes.sh" 0.4.2 "$T/dist"
		notes="$OUT"
		expect_contains "…opening on the changelog body" "$notes" "- A thing that was broken."
		expect_contains "…with the assets table" "$notes" "| Asset | Platform | SHA-256 |"
		expect_contains "…naming the archive" "$notes" "alter-zero-v0.4.2-$host.tar.gz"
		expect_contains "…linking its download" "$notes" "https://github.com/example/alter-zero/releases/download/v0.4.2/alter-zero-v0.4.2-$host.tar.gz"
		expect_contains "…with its hash" "$notes" "\`$(sha256_of "$archive")\`"
		expect_contains "…and the platform" "$notes" "$(platform_label "$host")"
		# shellcheck disable=SC2016 # the snippet's ${asset} is literal text for the reader
		expect_contains "…the install snippet" "$notes" 'sha256sum -c "${asset}.tar.gz.sha256"'
		expect_contains "…and the compare link" "$notes" "**Full changelog**: https://github.com/example/alter-zero/compare/v0.4.1...v0.4.2"

		section "publish --dry-run"
		expect_ok "a dry run needs no gh" env PATH="/nonexistent:$PATH" bash "$STEPS/publish.sh" 0.4.2 "$T/dist" --dry-run
		expect_contains "…printing the draft create" "$OUT" "gh release create v0.4.2 -R example/alter-zero --draft --verify-tag"
		expect_contains "…with the notes" "$OUT" "--notes-file"
		expect_contains "…and the publish flip" "$OUT" "gh release edit v0.4.2 -R example/alter-zero --draft=false --latest"
		if [ -f "$T/dist/SHA256SUMS" ]; then pass "…after writing SHA256SUMS"; else flunk "no SHA256SUMS written"; fi
		expect_ok "the dist still verifies with SHA256SUMS" bash "$STEPS/verify.sh" "$T/dist"
		expect_fail "publish refuses a dist that fails verify" bash "$STEPS/publish.sh" 0.4.2 "$T/dist-badsum" --dry-run
	else
		flunk "cc could not build the fixture binary: $(cat "$T/cc.log")"
	fi
else
	warn "no C compiler — skipping the package/verify/notes/publish cases"
fi

section "notes without assets"
expect_ok "notes render without a dist" bash "$STEPS/notes.sh" 0.4.1
expect_lacks "…with no assets table" "$OUT" "## Assets"
expect_contains "…and a first release links its commits" "$OUT" "**Full changelog**: https://github.com/example/alter-zero/commits/v0.4.1"
expect_fail "notes refuse an unknown version" bash "$STEPS/notes.sh" 0.9.9

# ---------------------------------------------------------------------------
section "prepare"
fixture "$T/prep" && cp "$T/pending/CHANGELOG.md" "$T/prep/CHANGELOG.md"
RELEASE_ROOT="$T/prep" RELEASE_DATE=2026-10-01 expect_ok "prepare rolls a fixture forward" bash "$STEPS/prepare.sh" 0.5.0
expect_eq "…Cargo.toml bumped (dependencies untouched)" "0.5.0 9.9.9" "$(RELEASE_ROOT="$T/prep" manifest_version) $(grep -c '"9.9.9"' "$T/prep/Cargo.toml" >/dev/null && echo 9.9.9)"
expect_eq "…Cargo.lock's crate entry bumped" "0.5.0" "$(RELEASE_ROOT="$T/prep" lock_version alter-zero)"
expect_eq "…the other lock entries untouched" "8.8.8" "$(RELEASE_ROOT="$T/prep" lock_version version)"
expect_eq "…README badge bumped" "0.5.0 0.5.0" "$(RELEASE_ROOT="$T/prep" readme_badge_version) $(RELEASE_ROOT="$T/prep" readme_alt_version)"
expect_eq "…the license badge untouched" "1" "$(grep -c 'License-Apache--2.0' "$T/prep/README.md")"
expect_eq "…changelog heading dated" "2026-10-01" "$(RELEASE_ROOT="$T/prep" changelog_date 0.5.0)"
expect_eq "…taking the pending body" "### Added

- Not yet rolled." "$(RELEASE_ROOT="$T/prep" changelog_section 0.5.0)"
expect_eq "…leaving [Unreleased] empty" "" "$(RELEASE_ROOT="$T/prep" changelog_section Unreleased)"
expect_eq "…older sections intact" "### Fixed

- A thing that was broken." "$(RELEASE_ROOT="$T/prep" changelog_section 0.4.2)"
expect_eq "…compare link added" "https://github.com/example/alter-zero/compare/v0.4.2...v0.5.0" "$(RELEASE_ROOT="$T/prep" changelog_link 0.5.0)"
expect_eq "…[Unreleased] re-pointed" "https://github.com/example/alter-zero/compare/v0.5.0...HEAD" "$(RELEASE_ROOT="$T/prep" changelog_link Unreleased)"
RELEASE_ROOT="$T/prep" expect_ok "…and the tree checks out for its tag" bash "$STEPS/check.sh" v0.5.0
expect_eq "…heading order: Unreleased, 0.5.0, 0.4.2, 0.4.1" "0.5.0 0.4.2 0.4.1" "$(RELEASE_ROOT="$T/prep" changelog_versions | tr '\n' ' ' | sed 's/ $//')"

RELEASE_ROOT="$T/prep" expect_fail "prepare refuses the current version" bash "$STEPS/prepare.sh" 0.5.0
RELEASE_ROOT="$T/prep" expect_fail "prepare refuses an empty [Unreleased]" bash "$STEPS/prepare.sh" 0.6.0
expect_contains "…and says why" "$OUT" "[Unreleased] section is empty"
RELEASE_ROOT="$T/prep" expect_fail "prepare refuses a non-semver version" bash "$STEPS/prepare.sh" 0.6
RELEASE_ROOT="$T/prep" expect_fail "prepare refuses a version already in the changelog" bash "$STEPS/prepare.sh" 0.4.1

fixture "$T/first"
awk '/^## \[Unreleased\]$/ { print; print ""; print "- First."; next } { print }' <<'EOF' >"$T/first/CHANGELOG.md"
# Changelog

## [Unreleased]

[Unreleased]: https://github.com/example/alter-zero/commits/HEAD
EOF
RELEASE_ROOT="$T/first" RELEASE_DATE=2026-10-01 expect_ok "prepare handles a first release" bash "$STEPS/prepare.sh" 0.5.0
expect_eq "…linking the tag, with nothing to compare against" "https://github.com/example/alter-zero/releases/tag/v0.5.0" "$(RELEASE_ROOT="$T/first" changelog_link 0.5.0)"

# ---------------------------------------------------------------------------
printf '\n%d passed, %d failed\n' "$PASS" "$FAILED"
[ "$FAILED" -eq 0 ]
