//! The public API surface of [`alter_zero::app`] and [`alter_zero::ui`].
//!
//! Both were single files once; they are now module trees whose `mod.rs`
//! re-exports each area by name (see `docs/module-layout.md`). An explicit
//! re-export list is auditable, but it can also *forget* a symbol — and because
//! `main.rs` only uses part of the surface, a dropped export compiles fine until
//! something reaches for it.
//!
//! So this file names every item the pre-split `app.rs`/`ui.rs` exported. It is a
//! compile-time assertion: if a re-export goes missing, or an item is moved
//! between modules without updating the facade, this test stops building. The
//! bodyless test exists only to give the failure somewhere to be reported.

// --- `app` — conversation state ---
#[rustfmt::skip]
#[allow(unused_imports)]
use alter_zero::app::{
    Action,
    AgentGroup,
    AgentGroupEntry,
    AgentGroupLive,
    AgentNotice,
    AgentStop,
    App,
    AskAnswerState,
    AskInput,
    AskPrompt,
    AskRow,
    BackgroundNotice,
    BackgroundShell,
    BackgroundView,
    Backtrack,
    BgCompletion,
    CommandEffect,
    CommandMenu,
    Compaction,
    FileSearch,
    DeviceLogin,
    DeviceStatus,
    DonatePicker,
    DonationAddress,
    HistoryItem,
    HistorySearch,
    HooksLevel,
    HooksMenu,
    InputHistory,
    InterruptedTurn,
    KeyKind,
    KeyOnboarding,
    KeyStep,
    LoginMethod,
    Look,
    LookFile,
    Mascot,
    MascotFile,
    MascotPicker,
    MascotRow,
    McpAuthView,
    McpMenu,
    McpOp,
    McpPage,
    McpServerAction,
    Message,
    ModelFetchError,
    ModelLoad,
    ModelPicker,
    PathDisplay,
    PermissionPrompt,
    ProviderChoice,
    QueuedTurn,
    Reasoning,
    ResumeControl,
    ResumeFilter,
    ResumePicker,
    ResumeSort,
    RetryInfo,
    Role,
    SigninKind,
    SearchState,
    SessionInfo,
    SettingRow,
    SettingsPicker,
    SkillMenuRow,
    SkillPicker,
    SkillsMenu,
    SlashCommand,
    Spinner,
    SpinnerFile,
    SpinnerPicker,
    SpinnerRow,
    StreamError,
    SubscriptionChoice,
    TaskCallRecord,
    Theme,
    ThemePicker,
    ThemeRow,
    ThinkingState,
    Toast,
    ToastKind,
    TokenArrow,
    ToolCall,
    TrustMenu,
    ToolStatus,
    TurnStatus,
    TurnSummary,
    View,
    DebugPage,
    AGENT_STOPPED_OUTPUT,
    CHECKPOINT_RESTORED_NOTICE,
    CHECKPOINT_REWOUND_NOTICE,
    COMMANDS,
    DONATION_ADDRESSES,
    COMPACT_BUSY_NOTICE,
    COMPACT_EMPTY_NOTICE,
    COMPACT_VERB,
    COPY_EMPTY_NOTICE,
    COPY_OK_NOTICE,
    DONE_VERBS,
    ERROR_TOOL_OUTPUT,
    HELP_BUSY_NOTICE,
    INIT_BUSY_NOTICE,
    INIT_PROMPT,
    INTERRUPT_NOTICE,
    INTERRUPT_TOOL_OUTPUT,
    RESUME_BUSY_NOTICE,
    SHELL_EMPTY_NOTICE,
    SHELL_VERB,
    WORKING_VERBS,
    ask_row_number,
    ask_rows,
    command_query,
    matching_commands,
    parse_theme_file,
    server_actions,
    shell_query,
    theme_file_json,
};

// --- `stream` — the backend seam and the offline dummy ---
// `stream.rs` was a single file too, and it split the same way (see
// `docs/module-layout.md`): the protocol, the trait, the cancel flag and the
// dummy demo are separate modules behind a by-name facade. Every symbol it
// exported before that split is named here.
#[rustfmt::skip]
#[allow(unused_imports)]
use alter_zero::stream::{
    AgentCallDone,
    AgentSpec,
    CancelToken,
    DummyAi,
    ReplySource,
    StallAi,
    StreamEvent,
    TokenUsage,
    ToolCallSummary,
    AGENT_DELAY,
    CHUNK_DELAY,
    STARTUP_DELAY,
    THINK_CHUNK_DELAY,
    TOOL_DELAY,
    chunks,
    dummy_response,
    image_ack,
    turn_events,
};

// --- `skills` — the `Skill` tool's pure model (docs/skills.md) ---
#[rustfmt::skip]
#[allow(unused_imports)]
use alter_zero::skills::{
    MentionToken,
    ParsedSkill,
    ProjectSkills,
    SkillError,
    SkillMatch,
    SkillMetadata,
    SkillParseError,
    SkillRegistry,
    SkillsFile,
    COMMON_ENV_VARS,
    DEFAULT_LISTING_BUDGET,
    MAX_LISTING_DESC_CHARS,
    MAX_SKILL_NAME_LEN,
    SKILL_BODY_MAX_BYTES,
    SKILL_FILE_NAME,
    SKILL_LOADED_DISPLAY,
    SKILL_MENTION_PREFIX,
    SKILL_TOOL_DISPLAY,
    SKILL_LISTING_HEADER,
    SKILL_TOOL_NAME,
    SKILL_TRUNCATION_MARKER,
    is_skill_tool,
    listing_budget,
    listing_message,
    mention_token,
    parse_skill,
    rank_skills,
    render_skill_body,
    shell_flavored_query,
    skill_listing,
    substitute_arguments,
    unreported_errors,
    validate_skill_name,
};

// --- `subagents` — the agent definitions' pure model (docs/subagents.md) ---
#[rustfmt::skip]
#[allow(unused_imports)]
use alter_zero::subagents::{
    AGENTS_DIR_NAME,
    AGENT_FILE_EXT,
    AGENT_LISTING_HEADER,
    ALL_TOOLS,
    AgentDefinition,
    AgentFileError,
    AgentModel,
    AgentParseError,
    AgentTools,
    INHERIT_MODEL,
    MAX_AGENT_NAME_LEN,
    SubagentRegistry,
    agent_budget,
    agent_listing,
    parse_agent,
    reminder_message,
    system_prompt_for,
    unknown_agent_message,
    unreported_errors as unreported_agent_errors,
    validate_agent_name,
    withheld_tool_message,
};

// --- `frontmatter` — the `---` block parse both authored formats share ---
#[rustfmt::skip]
#[allow(unused_imports)]
use alter_zero::frontmatter::{
    FileError,
    field,
    scalars,
    split,
    truncate_chars,
    unreported,
};

// --- `tasks` — the task tools' pure model (docs/task-tools.md) ---
#[rustfmt::skip]
#[allow(unused_imports)]
use alter_zero::tasks::{
    CreateArgs,
    GetArgs,
    Task,
    TaskRegistry,
    TaskCounts,
    TaskStatus,
    TaskStore,
    UpdateArgs,
    TASK_CREATE_TOOL,
    TASK_GET_TOOL,
    TASK_LIST_TOOL,
    TASK_TOOL_NAMES,
    TASK_UPDATE_TOOL,
    is_task_tool,
    task_display_name,
};

// --- `ui` — rendering ---
#[rustfmt::skip]
#[allow(unused_imports)]
use alter_zero::ui::{
    Repin,
    StreamRender,
    TranscriptCache,
    ViewFlow,
    COMPACTED_NOTICE,
    LIVE_MIN_HEIGHT,
    activate_theme,
    active_theme,
    agent_group_lines,
    agent_hint_line,
    agent_list_lines,
    agent_list_rows,
    agent_notice_lines,
    agent_transcript_lines,
    agent_view_status,
    background_notice_lines,
    background_view_height,
    background_view_lines,
    backtrack_hint_line,
    backtrack_scroll,
    backtrack_scroll_for,
    band_rows,
    banner_tail,
    centered_window,
    command_menu_lines,
    compaction_lines,
    classifier_lines,
    context_lines,
    ContextCache,
    ask_height,
    ask_lines,
    conversation_lines,
    cursor_position,
    display_cwd,
    donate_picker_height,
    donate_view_lines,
    file_menu_lines,
    file_menu_rows,
    footer_line,
    footer_rows,
    format_elapsed,
    format_token_count,
    header_lines,
    hooks_menu_height,
    mcp_menu_height,
    hooks_view_lines,
    mcp_view_lines,
    key_onboarding_height,
    live_agent_group_lines,
    live_height,
    mascot_picker_height,
    menu_rows,
    menu_window,
    message_lines,
    modal_needs_rebuild,
    model_picker_height,
    permission_height,
    permission_lines,
    permission_remember_label,
    preview_rows,
    queued_lines,
    queued_rows,
    reasoning_lines,
    render_ask,
    render_background_view,
    render_context_view,
    render_donate_picker,
    render_hooks_menu,
    render_mcp_menu,
    render_trust_menu,
    render_key_onboarding,
    render_live,
    render_live_with_preview,
    render_mascot_picker,
    render_model_picker,
    render_permission,
    render_resume_picker,
    render_settings,
    render_skills_menu,
    render_spinner_picker,
    render_theme_picker,
    render_tool_view,
    repaint_lines,
    repaint_tail,
    repin,
    restore_cursor_row,
    search_line,
    settings_height,
    shell_mode_line,
    skill_menu_lines,
    skill_menu_rows,
    skills_menu_height,
    spinner_picker_height,
    theme_picker_height,
    checklist_lines,
    idle_task_lines,
    image_block_lines,
    image_lines,
    item_images,
    shortcuts_lines,
    shortcuts_rows,
    startup_notice_lines,
    startup_paragraph_lines,
    status_line,
    status_line_with_verb,
    stream_preview_max_rows,
    strip_has_status,
    styled_status_line,
    summary_lines,
    task_rows,
    toast_line,
    toast_rows,
    tool_lines,
    tool_view_body_rows,
    tool_view_max_scroll,
    tool_view_max_scroll_for,
    transcript_lines,
    transcript_selection,
    trust_menu_height,
    trust_view_lines,
    view_body_skip,
    view_flow,
    view_flow_signature,
    with_theme,
    wrap_text,
};

/// Bodyless on purpose: the `use` declarations above are the assertion, and this
/// gives `cargo test` a name to report if they stop resolving.
#[test]
fn every_pre_split_public_symbol_is_still_reachable() {}
