//! The public API surface of [`alter_zero::app`] and [`alter_zero::ui`].
//!
//! Both were single files once; they are now module trees whose `mod.rs`
//! re-exports each area by name (see `docs/module-layout.md`). An explicit
//! re-export list is auditable, but it can also *forget* a symbol — and because
//! `main.rs` only uses part of the surface, a dropped export compiles fine until
//! something reaches for it.
//!
//! So this file names every item the pre-split `app.rs`/`ui.rs` exported. It is a
//! compile-time assertion: if a re-export goes missing, or an item is moved
//! between modules without updating the facade, this test stops building. The
//! bodyless test exists only to give the failure somewhere to be reported.

// --- `app` — conversation state ---
#[rustfmt::skip]
#[allow(unused_imports)]
use alter_zero::app::{
    Action,
    AgentGroup,
    AgentGroupEntry,
    AgentGroupLive,
    AgentNotice,
    App,
    BackgroundNotice,
    BackgroundShell,
    BackgroundView,
    Backtrack,
    BgCompletion,
    CommandEffect,
    CommandMenu,
    Compaction,
    FileSearch,
    HistoryItem,
    HistorySearch,
    InputHistory,
    InterruptedTurn,
    KeyOnboarding,
    KeyStep,
    Message,
    ModelFetchError,
    ModelLoad,
    ModelPicker,
    PermissionPrompt,
    ProviderChoice,
    QueuedTurn,
    Reasoning,
    ResumeControl,
    ResumeFilter,
    ResumePicker,
    ResumeSort,
    RetryInfo,
    Role,
    SearchState,
    SessionInfo,
    SlashCommand,
    StreamError,
    ThinkingState,
    Toast,
    ToastKind,
    TokenArrow,
    ToolCall,
    ToolStatus,
    TurnStatus,
    TurnSummary,
    View,
    AGENT_STOPPED_OUTPUT,
    CHECKPOINT_RESTORED_NOTICE,
    CHECKPOINT_REWOUND_NOTICE,
    COMMANDS,
    COMPACT_BUSY_NOTICE,
    COMPACT_EMPTY_NOTICE,
    COMPACT_VERB,
    COPY_EMPTY_NOTICE,
    COPY_OK_NOTICE,
    DONE_VERBS,
    ERROR_TOOL_OUTPUT,
    HELP_BUSY_NOTICE,
    INIT_BUSY_NOTICE,
    INIT_PROMPT,
    INTERRUPT_NOTICE,
    INTERRUPT_TOOL_OUTPUT,
    RESUME_BUSY_NOTICE,
    SHELL_EMPTY_NOTICE,
    SHELL_VERB,
    WORKING_VERBS,
    command_query,
    matching_commands,
    shell_query,
};

// --- `stream` — the backend seam and the offline dummy ---
// `stream.rs` was a single file too, and it split the same way (see
// `docs/module-layout.md`): the protocol, the trait, the cancel flag and the
// dummy demo are separate modules behind a by-name facade. Every symbol it
// exported before that split is named here.
#[rustfmt::skip]
#[allow(unused_imports)]
use alter_zero::stream::{
    AgentCallDone,
    AgentSpec,
    CancelToken,
    DummyAi,
    ReplySource,
    StallAi,
    StreamEvent,
    TokenUsage,
    ToolCallSummary,
    AGENT_DELAY,
    CHUNK_DELAY,
    STARTUP_DELAY,
    THINK_CHUNK_DELAY,
    TOOL_DELAY,
    chunks,
    dummy_response,
    image_ack,
    turn_events,
};

// --- `ui` — rendering ---
#[rustfmt::skip]
#[allow(unused_imports)]
use alter_zero::ui::{
    Repin,
    StreamRender,
    TranscriptCache,
    COMPACTED_NOTICE,
    LIVE_MIN_HEIGHT,
    agent_group_lines,
    agent_hint_line,
    agent_list_lines,
    agent_list_rows,
    agent_notice_lines,
    agent_transcript_lines,
    agent_view_status,
    background_notice_lines,
    background_view_height,
    background_view_lines,
    backtrack_hint_line,
    backtrack_scroll,
    backtrack_scroll_for,
    band_rows,
    banner_tail,
    centered_window,
    command_menu_lines,
    compaction_lines,
    context_lines,
    context_view_max_scroll,
    conversation_lines,
    cursor_position,
    display_cwd,
    file_menu_lines,
    file_menu_rows,
    footer_line,
    footer_rows,
    format_elapsed,
    format_token_count,
    header_lines,
    key_onboarding_height,
    live_agent_group_lines,
    live_height,
    menu_rows,
    menu_window,
    message_lines,
    modal_needs_rebuild,
    model_picker_height,
    permission_height,
    permission_lines,
    permission_remember_label,
    preview_rows,
    queued_lines,
    queued_rows,
    reasoning_lines,
    render_background_view,
    render_context_view,
    render_key_onboarding,
    render_live,
    render_live_with_preview,
    render_model_picker,
    render_permission,
    render_resume_picker,
    render_tool_view,
    repaint_budget,
    repaint_lines,
    repaint_tail,
    repin,
    restore_cursor_row,
    search_line,
    shell_mode_line,
    shortcuts_lines,
    shortcuts_rows,
    status_line,
    stream_preview_max_rows,
    strip_has_status,
    summary_lines,
    toast_line,
    toast_rows,
    tool_lines,
    tool_view_body_rows,
    tool_view_max_scroll,
    tool_view_max_scroll_for,
    transcript_lines,
    transcript_selection,
    wrap_text,
};

/// Bodyless on purpose: the `use` declarations above are the assertion, and this
/// gives `cargo test` a name to report if they stop resolving.
#[test]
fn every_pre_split_public_symbol_is_still_reachable() {}
